[2025-04-29T08:10:24.092+0000] {processor.py:156} INFO - Started process (PID=187) to work on /opt/airflow/dags/test_dag.py
[2025-04-29T08:10:24.093+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-29T08:10:24.094+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:10:24.094+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-29T08:10:24.103+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:10:24.102+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from airflow.operators  import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2025-04-29T08:10:24.103+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-29T08:10:24.126+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2025-04-29T08:10:54.835+0000] {processor.py:156} INFO - Started process (PID=225) to work on /opt/airflow/dags/test_dag.py
[2025-04-29T08:10:54.837+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-29T08:10:54.837+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:10:54.837+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-29T08:10:54.840+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:10:54.839+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from airflow.operators  import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2025-04-29T08:10:54.840+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-29T08:10:54.857+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2025-04-29T08:11:24.899+0000] {processor.py:156} INFO - Started process (PID=262) to work on /opt/airflow/dags/test_dag.py
[2025-04-29T08:11:24.900+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-29T08:11:24.900+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:24.900+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-29T08:11:24.903+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:24.902+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from airflow.operators  import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2025-04-29T08:11:24.903+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-29T08:11:24.916+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/test_dag.py took 0.019 seconds
[2025-04-29T08:11:55.624+0000] {processor.py:156} INFO - Started process (PID=301) to work on /opt/airflow/dags/test_dag.py
[2025-04-29T08:11:55.628+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-29T08:11:55.628+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:55.628+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-29T08:11:55.632+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:55.631+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from airflow.operators  import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2025-04-29T08:11:55.633+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-29T08:11:55.651+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2025-04-29T08:12:26.176+0000] {processor.py:156} INFO - Started process (PID=338) to work on /opt/airflow/dags/test_dag.py
[2025-04-29T08:12:26.176+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-29T08:12:26.177+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:12:26.177+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-29T08:12:26.180+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:12:26.179+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from airflow.operators  import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2025-04-29T08:12:26.180+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-29T08:12:26.197+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2025-04-29T08:12:50.419+0000] {processor.py:156} INFO - Started process (PID=375) to work on /opt/airflow/dags/test_dag.py
[2025-04-29T08:12:50.423+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-29T08:12:50.423+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:12:50.423+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-29T08:12:50.425+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-29T08:12:50.438+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/test_dag.py took 0.021 seconds
[2025-04-29T08:13:21.286+0000] {processor.py:156} INFO - Started process (PID=413) to work on /opt/airflow/dags/test_dag.py
[2025-04-29T08:13:21.287+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-29T08:13:21.287+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:13:21.287+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-29T08:13:21.288+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-29T08:13:21.299+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/test_dag.py took 0.016 seconds
